### ISSUE TITLE
Couldn't find preset "functional-hmr" relative to directory "MyApp/storybook"

### ISSUE THREAD

**Issue by RobIsHere** [bvic23/babel-plugin-functional-hmr#2]
For storybook it looks like packager doesn't find it. Maybe just a small thing? Do you know the reason?

This is in a brand new app and brand new install of storybook

````
ERROR in ./storybook/addons.js
Module build failed: Error: Couldn't find preset "functional-hmr" relative to directory "/Users/myuser/Documents/Investegy/storybook"
    at /Users/myuser/Documents/Investegy/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/myuser/Documents/Investegy/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/myuser/Documents/Investegy/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/myuser/Documents/Investegy/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/myuser/Documents/Investegy/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/myuser/Documents/Investegy/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/myuser/Documents/Investegy/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/myuser/Documents/Investegy/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/myuser/Documents/Investegy/node_modules/babel-loader/lib/index.js:49:20)
 @ multi ./storybook/addons.js ./node_modules/@storybook/react-native/dist/manager/index.js
````

**Comment by bvic23** [comment]
@RobIsHere thank for raising this issue!

It is interesting because I developed this plugin to improve storybook based development. 

Did you add it with:

```js
npm install --save-dev babel-plugin-functional-hmr
````

Could you verify `package.json` contains the line

```json
 "babel-plugin-functional-hmr": "^1.0.20",
```

in the `devDependencies` section?

You could also try to reset everything:

```bash
rm -rf node_modules/
yarn install
watchman watch-del-all
rm -rf $TMPDIR/react-*
./node_modules/react-native/packager/packager.sh --reset-cache
```

**Comment by RobIsHere** [comment]
And that's where I found the link to you! Great idea!

I already tried a lot of things, also clearing caches. 

The error says that it's looking at
"functional-hmr" relative to directory "MyApp/storybook"

While I would have expected that it looks in the base dir of my App? Like this?
"functional-hmr" relative to directory "MyApp"

**Comment by bvic23** [comment]
May I ask where did you find my plugin (the link you mentioned)?

I think I know what is the issue here, you set it as a `preset` but it's a `plugin` so your `.babelrc` should look like this:
```json
{
  "presets": ["react-native"],
  "plugins": ["functional-hmr"]
}
```

If this does not help, feel free to share your project with me.

**Comment by bvic23** [comment]
@RobIsHere Any updates?

**Comment by RobIsHere** [comment]
Thanks for the hint! Probably I had too much coffee yesterday. I've put it into plugins and the error message doesn't show up anymore.

I can't find the link anymore. I'm almost sure it was a comment by you at the end of some issue.

**Comment by bvic23** [comment]
Thanks for getting back, good luck!
